//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kosichkin_pr_18_v5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_table
    {
        public string Код { get; set; }
        public string Наименование_товара { get; set; }
        public decimal Цена_поступления { get; set; }
        public System.DateTime Дата_поступления { get; set; }
        public int Номер_партии { get; set; }
        public decimal Размер_партии { get; set; }
        public string Фирма_покупателя { get; set; }
        public decimal Размер_проданной_партии { get; set; }
        public decimal Цена_продажи { get; set; }
        public System.DateTime Дата_продажи { get; set; }
    }
}
