//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kosichkin_pr_18_v5
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentBase
    {
        public int Код { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Номер_зачётной_книжки { get; set; }
        public Nullable<bool> Живёт_ли_студен_в_общежитии { get; set; }
        public Nullable<bool> Математика { get; set; }
        public Nullable<bool> Экономика { get; set; }
        public Nullable<bool> Бух__учёт { get; set; }
        public Nullable<bool> Физ_ра { get; set; }
        public Nullable<bool> Англ__яз { get; set; }
        public Nullable<int> Индекс_группы { get; set; }
    }
}
