//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kosichkin_pr_18_v5
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentBase
    {
        public string Код { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Номер_зачётной_книжки { get; set; }
        public string Живёт_ли_студен_в_общежитии { get; set; }
        public string Математика { get; set; }
        public string Экономика { get; set; }
        public string Бух__учёт { get; set; }
        public string Физ_ра { get; set; }
        public string Англ__яз { get; set; }
    }
}
